version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: pdf-chatbot-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pdf-chatbot-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pdf-chatbot-backend
    volumes:
      - ./backend:/app
      - ./backend/public:/app/public
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - mongodb
    networks:
      - pdf-chatbot-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pdf-chatbot-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pdf-chatbot-network

networks:
  pdf-chatbot-network:
    name: pdf-chatbot-network

volumes:
  mongodb_data:
