version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8001:8000"  # Changed from 8000
    volumes:
      - ./:/app  # Attach volume for code
  frontend:
    image: nginx:alpine
    ports:
      - "81:80"  # Changed from 80
  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
